

export const ACTIONS = {
    GET_INPUT_VALUE: "GET_INPUT_VALUE",
    GET_VIDEO_REQUEST: "GET_VIDEO_REQUEST",
    GET_VIDEO_SUCCESS: "GET_VIDEO_SUCCESS",
    GET_VIDEO_FAILED: "GET_VIDEO_FAILED",
    GET_INPUT_VALUE_OMDB: "GET_INPUT_VALUE_OMDB",
    GET_VIDEO_OMDB_REQUEST: "GET_VIDEO_OMDB_REQUEST",
    GET_VIDEO_OMDB_SUCCESS: "GET_VIDEO_OMDB_SUCCESS",
    GET_VIDEO_OMDB_FAILED: "GET_VIDEO_OMDB_FAILED",
    GET_OMDB_ID: "GET_OMDB_ID",
    GET_ALL_ABOUT_FILM: "GET_ALL_ABOUT_FILM",
    SHOW_DETAILS: "SHOW_DETAILS",
    CLOSE_MODAL: "CLOSE_MODAL",
    GET_VIDEO_OMDB_PAGINATION_SUCCESS: "GET_VIDEO_OMDB_PAGINATION_SUCCESS",
    GET_VIDEO_OMDB_PAGINATION: "GET_VIDEO_OMDB_PAGINATION"
}